In [2]:
import numpy as np


In [3]:
# question 1
sales = np.array([[1200, 1400, 800, 1100],[1300,1500,1600,1000],[1100,1200,1000,1050]])
sales

array([[1200, 1400,  800, 1100],
       [1300, 1500, 1600, 1000],
       [1100, 1200, 1000, 1050]])

In [4]:
#quetion 2
cities = np.array(['Dallas', 'Houston', 'Austin'])
Quaters= np.array(['Q1','Q2','Q3', 'Q4'])
cities,Quaters

(array(['Dallas', 'Houston', 'Austin'], dtype='<U7'),
 array(['Q1', 'Q2', 'Q3', 'Q4'], dtype='<U2'))

In [5]:
#question 3
city=input("what is the city")
cities == city

what is the cityHouston


array([False,  True, False])

In [6]:
#quesiton 4
city = input ("what is the city")
sales[cities == city]

what is the cityHouston


array([[1300, 1500, 1600, 1000]])

In [7]:
#question 5
city = input ("what is the city")
sales[cities  ==city].sum(),sales[cities ==city].mean()


what is the cityHouston


(5400, 1350.0)

In [8]:
#question 6

quarter= input("which quarter?")


which quarter?Q2


In [10]:
#question 7
quater =input("which quarter?")
sales [:, quater== Quaters]

which quarter?Q2


array([[1400],
       [1500],
       [1200]])

In [11]:
#quetion 8
Quater =input("which Quarter?")
np.amax(sales[:,Quater==Quaters])

which Quarter?Q1


1300

In [13]:
#Question 9
np.amax(sales,axis =1)

array([1400, 1600, 1200])

In [14]:
#Quetion 10
np.amax(sales,axis=0)

array([1300, 1500, 1600, 1100])

In [15]:
#Question 11
sales.T

array([[1200, 1300, 1100],
       [1400, 1500, 1200],
       [ 800, 1600, 1000],
       [1100, 1000, 1050]])